check for 2 or more bg files before start

diff --git a/motquote b/motquote
--- a/motquote
+++ b/motquote
@@ -8,6 +8,11 @@ random_array_element() {
 
 # assign all files in the ./img/bg/ dir to array images
 images=(./img/bg/*)
+echo "${#images[@]}"
+if [ ${#images[@]} -lt 2 ]; then
+	echo "Two or more background images are required. Run prebg utility."
+	exit 1
+fi
 
 while read -r QUOTE; do
 	echo "Generating overlay for: ${QUOTE}"
@@ -26,8 +31,6 @@ while read -r QUOTE; do
 		BG_IMAGE="${images[RANDOM % ${#images[@]}]}"
 		#echo "${BG_IMAGE}"
 		
-		# resize background images, don't just preresize them before use
-
 		# overlay quote onto background
 		convert -page +0+0 "${BG_IMAGE}" \
 			-page +0+0 ./img/overlays/"${QUOTE_TITLE}"_overlay.png \
